### ISSUE TITLE
Failure to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by shifters67** [ZornsLemma/basictool#3]
Hi,

trying to compile on ubuntu 22.04 gives the following log and errors

make
c99 -g -O2 -Wall -Werror --std=c99 -c main.c
c99 -g -O2 -Wall -Werror --std=c99 -c config.c
c99 -g -O2 -Wall -Werror --std=c99 -c emulation.c
c99 -g -O2 -Wall -Werror --std=c99 -c driver.c
c99 -g -o bintoinc bintoinc.c
./bintoinc ../roms/EDITORA100 > zz-editor-a.c
./bintoinc ../roms/EDITORB100 > zz-editor-b.c
./bintoinc ../roms/Basic2 > zz-basic-2.c
./bintoinc ../roms/Basic432 > zz-basic-4.c
c99 -g -O2 -Wall -Werror --std=c99 -c roms.c
c99 -g -O2 -Wall -Werror --std=c99 -c utils.c
c99 -g -O2 -Wall -Werror --std=c99 -c lib6502.c
lib6502.c:952:34: error: argument 2 of type ‘char[124]’ with mismatched bound [-Werror=array-parameter=]
  952 | void M6502_dump(M6502 *mpu, char buffer[124])
      |                             ~~~~~^~~~~~~~~~~
In file included from lib6502.c:37:
lib6502.h:64:43: note: previously declared as ‘char[64]’
   64 | extern void   M6502_dump(M6502 *mpu, char buffer[64]);
      |                                      ~~~~~^~~~~~~~~~
lib6502.c: In function ‘M6502_dump’:
lib6502.c:957:103: error: ‘__builtin___sprintf_chk’ writing a terminating nul past the end of the destination [-Werror=format-overflow=]
  957 | %02X SP=%04X A=%02X X=%02X Y=%02X P=%02X %c%c%c%c%c%c%c%c elapsed: %d",
      |                                                                      ^

In file included from /usr/include/stdio.h:894,
                 from lib6502.c:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:38:10: note: ‘__builtin___sprintf_chk’ output between 65 and 79 bytes into a destination of size 64
   38 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   39 |                                   __glibc_objsize (__s), __fmt,
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   40 |                                   __va_arg_pack ());
      |                                   ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:51: lib6502.o] Error 1

**Comment by ZornsLemma** [comment]
Thanks for reporting this! I don't have an Ubuntu 22.04 machine handy to test on, but this looks like a simple error in lib6502.h. I've pushed a change to master, can you please give that a try and let me know if you still get any warnings/errors?

**Comment by shifters67** [comment]
Yes that fixes it fine - build with no errors

many thanks

Shifters

**Comment by ZornsLemma** [comment]
Good news, thanks!
