### ISSUE TITLE
linking fails on gcc 10.2.0: "multiple definition of `mpu_memory'"

### ISSUE THREAD

**Issue by scruss** [ZornsLemma/basictool#1]
On Ubuntu 20.10 (x86_64) compilation fails:

    make
    c99 -g -O2 -Wall -Werror --std=c99 -c main.c
    c99 -g -O2 -Wall -Werror --std=c99 -c config.c
    c99 -g -O2 -Wall -Werror --std=c99 -c emulation.c
    c99 -g -O2 -Wall -Werror --std=c99 -c driver.c
    c99 -g -O2 -Wall -Werror --std=c99 -c bintoinc.c
    c99 -g -o bintoinc bintoinc.o
    ./bintoinc ../roms/EDITORA100 > zz-editor-a.c
    ./bintoinc ../roms/EDITORB100 > zz-editor-b.c
    ./bintoinc ../roms/Basic432 > zz-basic.c
    c99 -g -O2 -Wall -Werror --std=c99 -c roms.c
    c99 -g -O2 -Wall -Werror --std=c99 -c utils.c
    c99 -g -O2 -Wall -Werror --std=c99 -c lib6502.c
    c99 -g -O2 -Wall -Werror --std=c99 -c cargs.c
    c99 -g -o ../basictool main.o config.o emulation.o driver.o roms.o utils.o lib6502.o cargs.o
    /usr/bin/ld: emulation.o:/home/scruss/Documents/src/basictool-0.01/src/emulation.h:11: multiple definition of `mpu_memory'; main.o:/home/scruss/Documents/src/basictool-0.01/src/emulation.h:11: first defined here
    /usr/bin/ld: driver.o:/home/scruss/Documents/src/basictool-0.01/src/emulation.h:11: multiple definition of `mpu_memory'; main.o:/home/scruss/Documents/src/basictool-0.01/src/emulation.h:11: first defined here
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:19: ../basictool] Error 1

gcc version: 

    c99 --version
    gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
    Copyright (C) 2020 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Removing the -W options doesn't change anything. Builds fine on Ubuntu 20.04 x86_64 (gcc 9.3.0) and Raspberry Pi OS armv7l
 (gcc 8.3.0).

**Comment by ZornsLemma** [comment]
Hi,

Thanks for reporting this. I think it's just a missing "extern" on the "M6502_Memory mpu_memory;" line in emulation.h. I've pushed a change to master which will hopefully fix this, can you please try it again? I haven't tagged this as a release yet but I can if it will help.

Cheers.

Steve

**Comment by scruss** [comment]
resolved, thanks!
